pool:
  name: 'Default'

trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature-*

variables:
  imageName: 'simpleapp:1.1.$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    docker login -u $(dockerId) -p $pswd
    docker push $(dockerId)/$(imageName)
    sed -i 's/simpleapp:latest/$(imageName)/g' dotnetapp-deployment.yaml
    sed -i 's/svc-master/svc-$(Build.SourceBranchName)/g' dotnetapp-deployment.yaml
  env:
    pswd: $(dockerPassword)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'dotnetapp-deployment.yaml' 
    artifactName: 'k8s'